# Generated by Django 3.1.1 on 2020-11-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='media/default.jpg', upload_to='user_photos/%y'),
        ),
    ]
