# Generated by Django 3.1.1 on 2020-11-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/default.jpg', upload_to='user_photos/%y'),
        ),
    ]
