# Generated by Django 3.1.1 on 2020-11-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_auto_20201107_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='backend\x07iims_e_learning_backend\\media\\default.jpg', upload_to='user_photos/%y'),
        ),
    ]
