# Generated by Django 3.1.1 on 2020-11-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_auto_20201107_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='user_photos/default.jpg', upload_to='user_photos/%y'),
        ),
    ]
