# Generated by Django 3.1.1 on 2020-12-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_auto_20201107_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
