name: aiims_e_learning
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  dio: ^3.0.10
  splashscreen:
  email_validator: ^1.0.5
  provider: ^4.3.2+2
  google_fonts: ^1.1.0
  carousel_slider: ^2.3.1
  flutter_search_bar: ^2.1.0
  video_player: ^0.10.12+4
  flutter_staggered_grid_view: ^0.3.2
  flick_video_player: ^0.1.1
  percent_indicator: "^2.1.7+2"
  advance_pdf_viewer: ^1.2.0
  fluttertoast: ^7.1.5
  timeline_tile: ^1.0.0
  uuid: ^2.2.2
  audioplayers: ^0.15.1
  flame: ^0.28.0
  
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/logo_1.png
    - assets/flutter_dev.png
    - images/dashboard.jpg
    - images/idea.png
    - images/courses.jpg
    - images/faculty.jpg
    - images/library.jpg
    - images/crap.jpg
    - images/book.png
    - images/library2.jpg
    - images/videos.jpg
    - images/test.jpg
    - images/libbook.jpg
    - images/play.png
    - images/teacher.jpg
    - images/cours.png
    - images/forum.jpg
    - images/blackbin.png
    - images/bg.png
    - assets/images/bg/bg.png
    - assets/images/flies/blackbin.png
    - assets/images/flies/blackbin_copy.png
    - assets/images/flies/bluebin_copy.png
    - assets/images/flies/redbin_copy.png
    - assets/images/flies/yellowbin_copy.png
    - assets/images/flies/greenbin_copy.png
    - assets/images/flies/whitebin_copy.png
    - images/apple.png
    - images/paper.png
    - images/papercup.png
    - images/banana.png
    - images/can.png
    - images/eggshell.png
    - images/bottle.png
    - images/garbage.png
    - images/tick.png
    - images/green_1.png
    - images/green_2.png
    - images/red_1.png
    - images/red_2.png
    - images/red_3.png
    - images/red_4.png
    - images/red_5.png
    - images/red_6.png
    - images/red_7.png
    - images/yellow_1.png
    - images/yellow_2.png
    - images/yellow_3.png
    - images/yellow_4.png
    - images/yellow_5.png
    - images/yellow_6.png
    - images/blue_1.png
    - images/blue_2.png
    - images/blue_3.png
    - images/white_1.png
    - images/white_2.png
    - images/white_3.png
    - images/white_4.png
    - images/black_1.png
    - images/black_2.png
    - images/black_3.png
    - images/black_4.png
    - images/black_5.png
    - assets/success.mp3
    - assets/images/kook.jpg
    - assets/images/kook.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
