# Generated by Django 3.1.1 on 2020-10-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(default=0, upload_to='faculty_photos/%y'),
            preserve_default=False,
        ),
    ]
