# Generated by Django 3.1.1 on 2020-12-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(default='settings.MEDIA_ROOT/faculty_photos/20/default.jpg', upload_to='faculty_photos/%y'),
        ),
    ]
