# Generated by Django 3.1.1 on 2020-12-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_auto_20201216_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(default='/faculty_photos/20/default.jpg', upload_to='faculty_photos/%y'),
        ),
    ]
