# Generated by Django 3.1.1 on 2020-10-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.CharField(default='very good', max_length=200),
            preserve_default=False,
        ),
    ]
