# Generated by Django 3.1.1 on 2020-12-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_questionofquiz_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.FileField(default='settings.MEDIA_ROOT/book.png', upload_to='thumbnail/%y'),
        ),
    ]
