# Generated by Django 3.1.1 on 2020-12-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.FileField(default='book.png', upload_to='thumbnail/%y'),
        ),
    ]
