# Generated by Django 3.1.1 on 2020-12-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20201216_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
